version: "3.7"

services:
  nginx:
    # If lua scripts are needed
    # image: openresty/openresty:1.13.6.1-alpine
    image: nginx:1.15.12-alpine
    ports:
      - "127.0.0.1:443:443"
    volumes:
      - "./nginx/etc/nginx:/etc/nginx/conf.d:ro"
      - "./nginx/etc/nginx/certs:/etc/nginx/certs:ro"
      - "./nginx/etc/openresty/nginx.conf:/etc/openresty/nginx.conf:ro"
    links:
      - "google-oauth"
    networks: 
      - test-net 
      - intranet
    # To prevent nginx from looping in case host has
    # 127.0.0.1    accounts.google.com
    dns:
      - 8.8.8.8
      - 8.8.4.4
    

  google-oauth:
    build: ./google-oauth
    environment:
      # - DEBUG=*
      - DEBUG=goauth
      - DOMAIN=${DOMAIN}
    networks:
      - intranet

networks:
  test-net:
    external: true
    name: ${NETWORK}
  intranet:
